### ISSUE TITLE
Help troubleshooting connection timeouts

### ISSUE THREAD

**Issue by kaitlynbrown** [nats-io/nats.js#332]
I have an electron app used by a number of clients to connect to our service.

The electron app sends http requests to our API using axios and connects to our NATS server using stan.js (I'm asking the question here however since stan.js is just a wrapper around nats.js, and the issue definitely isn't in the stan.js library).

In our internal testing of the app, we haven't encountered any connection issues. Every client we have sent the app to so far except one has been able to connect to NATS and receive messages with no problem.

The app of the client which is unable to connect to NATS *is* able to send http requests to our API with no problem. However, when their app attempts to connect to NATS, it times out. We have automatic retries set up, but it just keeps retrying over and over, and failing every time. I've tried increasing the connection timeout from 5s to 15s, however it still times out on every attempt.

I don't have access to the machine the app is running on, just logs which the client have sent that tell me the NATS connection is timing out, and there are no other errors.

What are some possible reasons for the connection timing out for this one client only? Keeping in mind that the app is still able to send requests to our HTTP API just fine with no errors. Is it possible that there is a network firewall that is blocking NATS traffic only? Are there some versions of Windows that this library doesn't work correctly on? Is there something I'm not thinking of that could be causing it?

**Comment by aricart** [comment]
@kaitlynbrown unfortunately, the default `maxReconnectAttempts` for the stan nats.js client is set to infinite (`-1`), which means the client is not giving up and giving an error we can see. It will simply disconnect and repeat whatever it did. If there's only one nats-server and it didn't get to exchange additional cluster URLs, it will not learn about other nats-servers it could connect to.

- Does your service ever connect on that machine?
- What kind of connection is it? TLS? Are certificates OK?
- What connection URLs do you provide, only one or is it failing to connect to any NATS cluster member? Hoping that you have a cluster otherwise it could be as you say that there's an issue on that particular machine where the specified nats-server cannot be accessed (firewall, network partition, dns, bad url, etc).
- Does the dns resolution on that machine resolve work to what you expect?
- The `clientID` provided on the stan connection is unique for all clients?
- Are you able to modify the code that client is using? (understanding yes because you changed the timeout)
- If you restart the service, does it connect?
- Do you have an `error` handler hooked-up `sc.on('error, (err) => {console.log(err})`?
- What is the network topology:
  - OS
  - versions of stan.js client
  - versions of nats.js client
  - Is the NATS-server embedded, on the nats-streaming-server?


You should try 'maxReconnectAttempts with 1 and see if the client emits an error that can guide you.

**Comment by kozlovic** [comment]
@kaitlynbrown Also, you assumes this is not STAN, but make sure that you are not getting a timeout due to the fact that the STAN connect times out because it does not receive the response from the server. A common cause is that the user provides the incorrect "cluster ID" as a connect option and the running STAN server(s) do not get the request (since the cluster ID is part of the subject space).

**Comment by aricart** [comment]
@kaitlynbrown I have not heard from you about this issue. Were you able to solve the issue?

**Comment by kaitlynbrown** [comment]
Not yet. I have been focused on other, more important tasks for now, as this issue is only affecting a single client - we've added a workaround for that one client to use. I'm hoping to have time to look into this issue more this week, however. Apologies for the delay in response

**Comment by kaitlynbrown** [comment]
We ended up deciding to switch to websockets since nats was causing too many headaches, and websockets are more versatile anyway. The client that was unable to connect via nats has no problems connecting on websokets, so I don't really have any way of testing / troubleshooting this issue any more. You can go ahead and close it if you like. Apologies if I wasted any if your time.

**Comment by aricart** [comment]
@kaitlynbrown sorry we were not able to resolve this issue for you.

**Comment by aricart** [comment]
@kaitlynbrown We identified a timeout issue with a recent nats.js release. However, the client you used for stan (assuming v0.2.6) didn't have this issue.
