### ISSUE TITLE
Performance issue with nats 2.0

### ISSUE THREAD

**Issue by mohantaylor** [nats-io/nats.js#438]
We recently swapped out our use of ts-nats for nats 2.x in a process that is quite latency sensitive and we've experienced some latency issues with the new lib.

The below code is a standalone example we put together to highlight the issue.  The below code (using **nats 2.1.0**) gives a round trip average time of about 3.2ms but when we run the same code (give of take a few minor syntax changes) using **ts-nats** we get an average of under 0.3ms.  Is this an issue with the new library or maybe we're not using the new package in the most optimal way?  Thanks for any assistance!

```
async function natsTest(): Promise<void> {
    const conn = await connect();

    conn.subscribe("testing", {
        callback: (err, msg) => {
            conn.publish(msg.reply as string, Uint8Array.from(Buffer.from("Hello rs")));
        }
    });

    const time = process.hrtime();
    const maxRuns = 1000;
    let runs = maxRuns;
    while (runs > 0) {
        const resp = await conn.request("testing", Uint8Array.from(Buffer.from("Hello req")), {
            timeout: 5000
        });
        const l = resp.data.toString();
        runs--;
    }
    console.log(process.hrtime(time));
}
```

**Comment by aricart** [comment]
yes - this kind of test doesn't do great because really if you think about it you are actually doing 2x (sender->server->sub->server->sender) the work - separating requestor and subscriber will do much better. In actual multi-process performance 

Async **IS** slower than event-driven (especially in node), but requiring a lot of the tricks (as your using of increasing timeouts, etc), and having more risk of getting shutdown (slow consumer) by the server when real load hits your client. If you want more detail about it, read this: https://github.com/nats-io/nats.deno#async-vs-callbacks

<google-sheets-html-origin>

Classic Node | 1,116,071 | 100.00% | 1,175,088 | 100.00% | 1,175,088 | 100.00%
-- | -- | -- | -- | -- | -- | --
Deno | 3,172,589 | 284.26% | 1,206,273 | 102.65% | 2,066,116 | 175.83%
WS (Chrome) | 2,597,403 | 232.73% | 1,042,753 | 88.74% | 1,408,451 | 119.86%
Node | 3,929,273 | 352.06% | 658,979 | 56.08% | 1,238,083 | 105.36%





If you want to go fast, you cannot block so in this kind of setup, this will be infinitely more scalable (ie the cost of doing a single message is 1/2 of doing all 1000 messages).

```javascript
const { connect, StringCodec} = require("../");

const sc = StringCodec();

async function run() {
  const nc = await connect();
  const sub = nc.subscribe("testing");
  (async () => {
    for await (const m of sub) {
      m.respond(m.data)
    }
  })().then()


  const start = process.hrtime();
  const proms = [];
  const N = 1000;
  const buf = sc.encode("Hello req");
  for (let i=0; i < N; i++) {
    const p = nc.request("testing", buf)
    proms.push(p);
  }

  const done = await Promise.all(proms);
  // check the resulting messages
  console.log(process.hrtime(start));
}

run();
```

**Comment by aricart** [comment]
Fixed by https://github.com/nats-io/nats.deno/pull/566
