### ISSUE TITLE
Can't use pullSubscribe with queue

### ISSUE THREAD

**Issue by Kingmoz** [nats-io/nats.js#448]
I am trying to create two consumers that listen to the same subject in the same queue group. When I start these two consumers, they both consumes the same messages which does not form a queue group correctly. 

Consumer 1:
```
  const js = nc.jetstream();

  const opts = consumerOpts();
  opts.queue("queue");
  opts.durable("1"); //
  opts.ackExplicit();
  opts.deliverAll();
  opts.manualAck();

  const sub = await js.pullSubscribe("subject", opts);

  await sub.pull();
  for await (const m of sub) {
    await m.ack();
    await sub.pull();
  }
```
Consumer 2:
```
  const js = nc.jetstream();

  const opts = consumerOpts();
  opts.queue("queue");
  opts.durable("2");
  opts.ackExplicit();
  opts.deliverAll();
  opts.manualAck();

  const sub = await js.pullSubscribe("subject", opts);

  await sub.pull();
  for await (const m of sub) {
    await m.ack();
    await sub.pull();
  }
```

nats-server: 2.4
nats.js: 2.2.0

**Comment by kozlovic** [comment]
First, with "pull subscribe", you should not need a queue since by definition, the subscription that will pull messages will get a batch of messages to itself alone, so 2 pull subscribers on the same durable work a bit like if they were a queue.

Second, your example above is incorrect since you use the same queue group name but for 2 different durables, so it is then expected that each queue subscriber receive the same message because they are feeding from different JetStream consumer ("1" and "2"). If you specify the same durable name, then you will see this work as you expect since then there will be 2 members of the same group feeding from the same durable consumer.

**Comment by aricart** [comment]
As Ivan described, pull consumers are effectively already in a queue group, so you should just have one, otherwise they will each get their _view_ on the stream and each process all messages.

In your case what you want to do is:

```typescript
  const { ns, nc } = await setup(jetstreamServerConf({}, true));
  const { stream, subj } = await initStream(nc);
  const jsm = await nc.jetstreamManager();
  const js = nc.jetstream();
  const buf: Promise<PubAck>[] = [];
  for (let i = 0; i < 100; i++) {
    buf.push(js.publish(subj, Empty));
  }
  await Promise.all(buf);

  let ci = await jsm.consumers.add(stream, {
    durable_name: "me",
    ack_policy: AckPolicy.Explicit,
  });
  assertEquals(ci.num_pending, 100);

  let countA = 0;
  let countB = 0;
  const m = new Map<number, number>();

  const opts = consumerOpts();
  opts.durable("me");
  opts.ackExplicit();
  opts.deliverAll();
  const subA = await js.pullSubscribe(subj, opts);
  (async () => {
    for await (const msg of subA) {
      const v = m.get(msg.seq) ?? 0;
      m.set(msg.seq, v + 1);
      countA++;
      msg.ack();
    }
  })().then();

  const subB = await js.pullSubscribe(subj, opts);
  (async () => {
    for await (const msg of subB) {
      const v = m.get(msg.seq) ?? 0;
      m.set(msg.seq, v + 1);
      countB++;
      msg.ack();
    }
  })().then();

  const done = deferred<void>();
  const interval = setInterval(() => {
    if (countA + countB < 100) {
      subA.pull({ expires: 500, batch: 25 });
      subB.pull({ expires: 500, batch: 25 });
    } else {
      clearInterval(interval);
      done.resolve();
    }
  }, 25);

  await done;

  ci = await jsm.consumers.info(stream, "me");
  assertEquals(ci.num_pending, 0);
  assert(countA > 0);
  assert(countB > 0);
  assertEquals(countA + countB, 100);

  for (let i = 1; i <= 100; i++) {
    assertEquals(m.get(i), 1);
  }

  await cleanup(ns, nc);
```

The test above, creates one consumer and two pull subscriptions (each attached to the same consumer). When a message is processed, each subscription tracks it, and updates a map storing the number of times a message sequence was seen. The expected result is that each sequence got seen once, and between the two subscriptions all messages were seen.
