### ISSUE TITLE
Jetstream and Request-Response not compatable?

### ISSUE THREAD

**Issue by saryana** [nats-io/nats.js#476]
We have set up a NATS request-response system and want to add a listening layer with some guarantee of delivery and we figured Jetstream would be perfect. When we added the stream with consumer and listener on the same subject, our request response system stops working. It appears that these two are not compatible?

jsmsg that appears to do this
```
    doAck(payload) {
        if (!this.didAck) {
            // all acks are final with the exception of +WPI
            this.didAck = !this.isWIP(payload);
            this.msg.respond(payload);
        }
    }
```

Sample code 
```
    const nc = await connect({})
    const jc = JSONCodec()
    // add a stream
    const stream  = 'stream1'
    const subj    = 'actual_subject'

    await jsm.streams.add({
        name     : stream,
        subjects : ['actual_subject.a'],
    })

    const rs = await nc.subscribe(`${subj}.a`);
    (async () => {
        for await (const m of rs) {
            console.log('subber')
            const req = jc.decode(m.data)
            console.log(req)
            m.respond(jc.encode({ ...req, response: true }))
        }

        console.log('subscription closed')
    })()
    
    for (let i = 0; i < 10; i++) {
        nc.request(`${subj}.a`, jc.encode({ payload: i }))
            .then(response => {
                console.log('resp')
                console.log(jc.decode(response.data))
            })
            .catch(ex => {
                console.log(ex)
            })
    }

    const opts1 = consumerOpts()
    opts1.queue('queue1')
    opts1.durable('durable1')
    opts1.deliverTo('here')
    opts1.callback((_err, m) => {
        console.log('sub1')
        console.log(jc.decode(m.data))
        if (m) {
            m.ack()
        }
    })
    
    const sub1 = await js.subscribe(`${subj}.a`, opts1)

```

With the output:
```
resp
{ stream: 'stream1', seq: 1 }
resp
{ stream: 'stream1', seq: 2 }
resp
{ stream: 'stream1', seq: 3 }
subber
{ payload: 0 }
subber
{ payload: 1 }
subber
{ payload: 2 }
sub1
{ payload: 0 }
sub1
{ payload: 1 }
sub1
{ payload: 2 }
```

**Comment by aricart** [comment]
@saryana the issue here is not that the message is getting swallowed, but rather the guy making the request is getting is processing the first response and it completes. In reality, two responses are being sent to your request - the response from JetStream `{setream: 'stream1', seq: 1}`, and the response to the service. Both are going to the same subject. The request operation resolves after the first message when it is received.

A few other notes: `const rs = await nc.subscribe(`${subj}.a`);` No await is required there, that is just a nats subscription. The messages delivered to the JetStream subscription have a different reply subject. The ack you are sending there is only going to the JetStream service.

**Comment by aricart** [comment]
If you want to see what I mean try this program instead:

```javascript
  const { ns, nc } = await setup(jetstreamServerConf({}, true));
  const { stream, subj } = await initStream(nc);
  const jc = JSONCodec();

  const opts = consumerOpts();
  opts.queue("q");
  opts.durable("d");
  opts.deliverTo("here");
  opts.ackExplicit();
  opts.callback((_err, m) => {
    assert(m);
    const jmi = m as JsMsgImpl;
    console.log(`js sub: ${m.subject} ${jmi.reply}`);
    m.ack();
  });
  const worker = await nc.jetstream().subscribe(subj, opts);

  const serv = nc.subscribe(subj, {
    callback: (err, m) => {
      assert(m)
      console.log(`srv: ${m.subject} ${m.reply}`);
      m.respond(jc.encode({id: jc.decode(m.data)}));
    },
  });

  const rsubj = "origreply"
  nc.subscribe(rsubj, {callback: (err, msg) => {
      console.log(`response: ${msg.subject} ${JSON.stringify(jc.decode(msg.data))}`)
  }});

  for(let i=0; i < 10; i++) {
    nc.publish(subj, jc.encode(i), {reply: rsubj})
  }

  await nc.flush();
  ```

The output looks like this:

```
// this is the service receiving a request
srv: 7JL8D390F0Z9WR9WJQGK1M.A origreply
// the requestor got a JetStream server response that the message was stored in the stream
// at this point your requestor is done, and you don't get the response you were expecting.
response: origreply {"stream":"7JL8D390F0Z9WR9WJQGK1M","seq":1}
// the jetstream subscription gets a message (the $JS.ACK... is the reply subject)
js sub: 7JL8D390F0Z9WR9WJQGK1M.A $JS.ACK.7JL8D390F0Z9WR9WJQGK1M.d.1.1.1.1643319266199519000.4
// the response generated by your service arrives later (or before depending on the order of things)
response: origreply {"id":0}
```

For what you are trying to do the architecture needs to a bit different:

- You probably want to publish a message to JetStream - the response from JetStream will tell you that the message was stored or failed storing. You may want this stream to be a workqueue. Meaning that it will remain on the stream until you ack it.

- Your service will be a JetStream worker, it will get the message from JetStream and the payload should indicate where you want to re-send the request, the worker should make a request to that subject. If you get 'acked' on that request, then you can proceed to ack the message from the stream and you know that the request was received and handled.

**Comment by saryana** [comment]
@aricart thanks for the very quick response and the example, it certainly highlights this much more clearly! 

I do still have an open question though, I was indeed hoping to use the promise based [Request/Reply](https://github.com/nats-io/nats.js#services-requestreply) API. I see in your example that you circumvent this by using a publish with reply subject and a subscription of that. I haven't looked at the internals of request response, but figure it would do something similar. So to rephrase my question, using the promise based request response alongside Jetstream it isn't possible; however, using a publish/subscribe with a response subject appears to be the suggested path forward?

**Comment by aricart** [comment]
@saryana the issue is that the nc.request() API is satisfied by the first response received. The subscription opened for the request closes as soon as the first response arrives.

It is on my list to make public a mechanism to scatter/gather - this is where you send a request, but expect N responses:

```javascript
export async function scatter<T>(
  nc: NatsConnection,
  subj: string,
  args?: Record<string, unknown>,
): Promise<T[]> {
  const nci = nc as NatsConnectionImpl;
  const jc = JSONCodec();
  const payload = args ? jc.encode(args) : Empty;
  const inbox = createInbox(nci.options.inboxPrefix || "");
  const buf: Msg[] = [];
  const sub = nc.subscribe(inbox);
  await nc.flush();
  nc.publish(subj, payload, { reply: inbox });
  let to = timeout(1000);
  const done = (async () => {
    for await (const m of sub) {
      buf.push(m);
      to.cancel();
      to = timeout(200);
      to.catch(() => {
        sub.unsubscribe();
      });
    }
  })().then();
  to.catch(() => {
    sub.drain();
  });
  await done;
  return buf.map((m: Msg) => {
    return jc.decode(m.data) as T;
  });
}
```

The quick answer to your question - whether a request/response makes sense in JetStream is probably _no_. You need to decide whether you are going to observe live data, or rely on persistence to audit your data.

Now with that said, perhaps the right thing for you is to create the stream by specifying the option `no_ack` - what this means is that the stream won't reply to your publishing (which is intended as a service request). That has the side effect that while the stream may capture your message, it is possible depending on the topology that the message update fails even if the requestor gets the request and responds to it. Likely you'll also want some standardized reply subject (you can use `noMux` and `reply` option on the request - that point to a different subject that falls within the scope of the stream for capture. 

The strategies are many, with varying levels of pain. Possibly the right thing to do is simply to have a request subject that is outside of the stream, the requestor then uses a stream to log the request and response before returning the value to you. That would be much simpler than any of the alternatives.
