### ISSUE TITLE
Have message in an array instead of an async iterator

### ISSUE THREAD

**Issue by matteodisabatino** [nats-io/nats.js#506]
I use NATS with Jetstream and pull consumers. As documentation specifies, I use this method to get messages:

```js
const jetstreamClient = natsConnection.jetstream()
const myConsumer = await jetstreamClient.pullSubscribe('myStream.mySubject', myOptions)
myConsumer.pull({ batch: limit })
for await (const message of myConsumer) {
    // Do something
}
```

Anyway, for some reasons, it would useful to me to have an array instead of an async iterator. I image something like that:

```js
const jetstreamClient = natsConnection.jetstream()
const myConsumer = await jetstreamClient.pullSubscribe('myStream.mySubject', myOptions)
const messages = await myConsumer.pull({ batch: limit })
for (const message of messages) {
    // Do something
}
```

Is there a a way to achieve that?

**Comment by aricart** [comment]
the quick answer on your sample above is you cannot, the reason for it is that the iterator you created is actually alive.
That iterator spans all the pulls you are going to make, as the pulls is what keeps it fed. The iterator only ends if you `break` or if you `unsubscribe()` on the pull subscription.

You can try using `fetch()` which will give you an iterator that will eventually finish (depending on the `expires`), and then you can forawait process that into an array, which you can then use for processing. But also note as you collect messages, if those messages have an ack policy, you could start running into redeliveries, as the fetch will not complete until it gets the specified number of messages or the expiration is reached.

**Comment by matteodisabatino** [comment]
Hi @aricart and thanks for your answer.

I've tried to use `fetch()` and it seems to solve my problem. But for what I have understood reading documentation and source code, with `fetch()` I cannot use queue groups, and I need this feature.

**Comment by aricart** [comment]
hi @matteodisabatino, queue groups are not necessary on pull consumers. The fetch/pull/etc, specifies a subscription to process the messages, so queue groups are not necessary there. Push consumers have queues because the server distributes messages between the members. 

One thing, because pull consumers a request base, you shouldn't make very large requests on the pull/fetch etc if you want to horizontally scale them, as you may send a lot of work to a single worker and nothing to the others. Yes you can use `working()` on a message, make sure that manual acks are set on the consumer option, or messages may be auto-acked for you when the dispatch/iteration for the message happens.

**Comment by matteodisabatino** [comment]
> queue groups are not necessary on pull consumers

This is wonderful! I didn't know that, I'll make some tests and I'll let you know (if all works, maybe, you can add an example on the readme)

Thanks for your clarity.

**Comment by matteodisabatino** [comment]
Hi @aricart, sorry for have been extremely late... I forgot to let you know 😅 

Anyway, you suggestions were perfect: i totally solved my problem. Thank you so much 😊
