### ISSUE TITLE
NatsError timeout while request

### ISSUE THREAD

**Issue by goldalworming** [nats-io/nats.js#540]
Hi, I have problem while request topic after subscriber worker run about 5-7 hours. 
the subscriber still shown access log but give no response. 
the requester get error
    "name": "NatsError",
    "code": "TIMEOUT"

it works again while I restart subscriber worker
I tried to show error log but no error in subscriber, only the requester always got timeout

anybody has faced same issue or idea to debug?

**Comment by aricart** [comment]
If the requester is getting a timeout, that means that either the request timeout option is set too low for the subscriber, or the request is made on the wrong subject. Would need to see the configuration for the subscription and the request.

**Comment by aricart** [comment]
Another possibility is that the subscription received a permissions error (if someone changed the permissions on you), and at that point, the subscription is done. So any requests would naturally end with a timeout. You can watch whether a subscription is active or not by monitoring the `closed` promise. If it resolves, the subscription closed:
```
const sub = nc.subscribe(subj, (err, msg) => { msg?.respond(); });
sub.closed.then(() => { console.log(`subscription closed`); }));
```

**Comment by goldalworming** [comment]
It seems memory usage hit the limit make subscription drain and close. can we drain the memory without end the app?

**Comment by aricart** [comment]
can you post the actual error your are hitting and where it is coming from?

**Comment by goldalworming** [comment]
const msub = nc.subscribe("kv.*",(err, msg) => { msg?.respond(); });
    (async (sub) => {
      console.log(`listening for ${sub.getSubject()} requests`);
      // it would be very good to verify the origin of the request
      // before implementing something that allows your service to be managed.
      // NATS can limit which client can send or receive on what subjects.
      let idx = 0
      for await (const m of sub) {
          //handling request here
          //....
      }
      console.log("last idx",idx)
      console.log(`subscription ${sub.getSubject()} drained.`);
      exec('start "" "'+"run.bat"+'"')
    })(msub);

![image](https://user-images.githubusercontent.com/440256/214243773-a301af2c-698f-4caa-b661-d1642448a55c.png)
this is some messages error I got

I tried to rerun .bat file while subscription end but got another error
I don't understand what makes  looping in `for await (const m of sub) ` end

**Comment by goldalworming** [comment]
since data getting bigger, error more frequent and I don't know how to debug in subscription
I've add `const sub = nc.subscribe(subj, (err, msg) => { msg?.respond(); });` but no error shown

**Comment by aricart** [comment]
I know exactly what is going on:
`const msub = nc.subscribe("kv.*",(err, msg) => { msg?.respond(); });`
Note you are passing a function directly to the subscription, the correct format is:
`const msub = nc.subscribe("kv.*",{callback: (err, msg) => { msg?.respond(); }});`

**Comment by aricart** [comment]
With that change, the other issue you are going to flush out, is that you are trying to handle messages both in a callback and in an iterator. The iterator will throw an error

**Comment by aricart** [comment]
The other thing that I see in your code is, possibly the reason for the timeouts:

```
  for await (const m of sub) {
      //handling request here
      //....
  }
```

The question is what happens in the for await - if you are awaiting inside of the loop, you will block the loop from processing messages until the iteration completes. So if there is an awaited operation there, you are effectively head of line blocking the processing. 

What that means is that you get 5 requests on your service. But the iteration on the loop takes 300ms. Default timeout for a request is 1s, this means that the first 2 or 3 will process fine, but 4 and 5 are very likely to be seen as a timeout on the client that sent the request.

**Comment by goldalworming** [comment]
![image](https://user-images.githubusercontent.com/440256/214496156-769f079c-3b1c-4e88-9e25-ad0fa3066b8e.png)
I've remove all await inside loop. It's better but still stoping at uncertain loop

**Comment by aricart** [comment]
without seeing more code I cannot help you, but check the client that is getting the timeout, and make sure that the timeout is consistent with the time you expect to get a response.

**Comment by aricart** [comment]
Also, what version of the client do you have, if you are not at the current version, please upgrade.

**Comment by goldalworming** [comment]
I use node 16 and nats 2.7.1

![image](https://user-images.githubusercontent.com/440256/214757627-9e8b8092-c9b3-48a0-b955-b6ff7ff090a9.png)
it just basic keyvalue read and write

**Comment by aricart** [comment]
Please update to the current version of the client (2.11.0) and server (2.9.12)

**Comment by goldalworming** [comment]
![image](https://user-images.githubusercontent.com/440256/222878639-0304ca8f-ee3e-4443-a3a4-f5012533a4cd.png)
 still got subscription drained in the middle of process
 
 is it memory problem or bug?
 I've add max memory when execute it
 
 node --max-old-space-size=1024 app-cache.js

**Comment by aricart** [comment]
Sure you can do a flush; the client can accumulate up to 32K in a single event loop before automatically flushing. Otherwise, it flushes on the next event loop. You can force a flush but that may degrade the performance, specially if you await that to complete before you process the next request.

Can you time once cycle through your loop, and also jetpack.read()/write() - while those functions are blocking in the async iterator, the network is reading more messages, so possbily the memory growth is in-bound. If that is the case you can try to things:

Try putting the logic of your operation in a function, and calling it without awaiting it - this will allow processing to start faster.  - Also call `sub.getPending()` to see how fast your subscription is getting additional messages. It is possible that you cannot process them on a single process that quickly, and will need to horizontally scale the subscription to be a queue subscriber. This will distribute the load between the subs.

Alternatively, instead of using an iterator, use a callback, messages won't be read from the network if you do that while you process in the callback, however you will be blocking the client, so if you are getting a lot of messages you will start seeing a slow consumer from the server (at that point you should be doing a queue subscriber) and add additional process to handle the load.

**Comment by goldalworming** [comment]
I give up using node.js and use python. It far more stable and has no issue for several days.

Thank You
