### ISSUE TITLE
How to specify "cluster_id" while creating a NATS JetStream connection?

### ISSUE THREAD

**Issue by bestofman** [nats-io/nats.js#548]
In nats-streaming I could create a nats connection via the following code:
```

import nats, { Stan } from 'node-nats-streaming';

private _client?: NATS.JetStreamClient;
this._client = nats.connect(clusterId, clientId, { url });
```

And with some modifications I could do the following for the newer JetStream:

    import NATS from "nats";
    
    private _client?: NATS.JetStreamClient;
    this._client = (await NATS.connect({ name: clientId, servers: url })).jetstream();

But it seems there is no `cluster_id` property between JetStream's `ConnectionOptions`!

So how can I create the same NATS client using the connection function using new NATS JetStream?

**Comment by aricart** [comment]
there's no cluster_id in jetstream as it was in nats streaming. There it was required because you needed to target where you were going to store data. In jetstream, if you want isolation you use accounts, you can also add tags to servers, and then provide those tags to JetStream to hint where you want things are stored.

For the clustering bit, see https://docs.nats.io/running-a-nats-service/configuration/clustering/jetstream_clustering
https://docs.nats.io/running-a-nats-service/configuration/resource_management

For accounts see https://docs.nats.io/running-a-nats-service/configuration/securing_nats/accounts

**Comment by bestofman** [comment]
> there's no cluster_id in jetstream as it was in nats streaming. There it was required because you needed to target where you were going to store data. In jetstream, if you want isolation you use accounts, you can also add tags to servers, and then provide those tags to JetStream to hint where you want things are stored.
> 
> For the clustering bit, see https://docs.nats.io/running-a-nats-service/configuration/clustering/jetstream_clustering https://docs.nats.io/running-a-nats-service/configuration/resource_management
> 
> For accounts see https://docs.nats.io/running-a-nats-service/configuration/securing_nats/accounts

So you say this is an improvement in JetStream and we no longer need to specify a cluster_ip except there is a real isolation concern.
