### ISSUE TITLE
What's the point of encode/decode?

### ISSUE THREAD

**Issue by avkulpin** [nats-io/nats.js#551]
I don't really understand why this low-level decoding/encoding feature was brought up to the very top api level. Instead of just publishing events with payload, a user now also has to manually decode/encode payload. Could you please clarify the rationale behind this move?

**Comment by aricart** [comment]
@avkulpin actually, this is a really good question

The reason why is that while your client may be encoding or decoding in some format, another client may be encoding in a format that won't even parse in what you are expecting. By having the client explicitly encode or decode, any exceptions thrown will be front an center on the user code rather than deep in the library.

**Comment by aricart** [comment]
One more, I have been considering for reading payloads to add utilities to `Msg` that handle JSON and string data. That would greatly benefit the client because you could:

```typescript
for await(const m of sub) {
   m.json();
   m.string();
}
```

This would still satisfy that if the code throws due to an encoding mismatch, the error is within the user code, but the library makes it easier. On the publish side, doesn't work as well because  each variant would effectively bloat the API.

While it may look strange, it is not without precedent. `JSON.stringify()/parse(), TextEncoder().encode(), TextDecoder().decode()` In the case of the library, perhaps the only one that is a bit superfluous is the StringCodec, but the instance of the encoder is shared, so it affords some additional optimization.

**Comment by aricart** [comment]
https://github.com/nats-io/nats.deno/issues/476

**Comment by aricart** [comment]
Added the helpers above for reading data - https://github.com/nats-io/nats.deno/issues/476
