### ISSUE TITLE
async generators and catching errors on yield

### ISSUE THREAD

**Issue by kirrg001** [nats-io/nats.js#552]
Hi there!

I'm working for an APM provider and we have already successfully instrumented nats@1. 
nats@1 is using callbacks. This works great with APMs - as well as promises etc.

nats@2 instroduced async generators to receive messages. We are no longer able to catch errors when the messages are received.

```js
const sub = nats.subscribe('any-subject');

async function receiveMessages() {
  for await (const m of sub) {
    // imagine any error here is thrown during runtime e.g. typeerror
    throw new Error('example')
  }
}
```

APM's will create a trace that a message was received via the nats library (entry). But we cannot tell if the message was successfully received or not if an error is thrown because we cannot catch it.

Trying to catch the error on `yield` is as far as I know **not possible by design with native async generators.**

```js
const createGenerator = function* () {
  try {
    yield 'msg';
  } catch (err) {
    console.log('NEVER CATCHED')
  }
};

const generator = createGenerator();
setTimeout(async () => {
  for await (const item of generator) {
    // typeerror conole
    conole.log(item);
  }
}, 1000)
```

[Yes, customers can register a global uncaught exception handler to catch the error themselfs, but that is not optimal for APMs.]

**Comment by aricart** [comment]
@kirrg001 currently, if there's an error, the async loop will throw.

Also note that while in Node, you may be able to register a global handler for that, this is not true of other runtimes. The base library is shared between Node, Deno, and websocket running on the browser. Because it is an async iterator, the expectation is that the client code will catch any exception that could be raised, so in node you could register your handler, the error will be descriptive of what went wrong:

```
sub failed NatsError: 'Permissions Violation for Subscription to "bar"'
    at Function.toError (file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/protocol.ts:415:19)
    at ProtocolHandler.processError (file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/protocol.ts:457:33)
    at ProtocolHandler.push (file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/protocol.ts:573:14)
    at Parser.parse (file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/parser.ts:352:31)
    at file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/protocol.ts:295:25

```

To put this in context, there are very few constructs where an async error is reported that is not terminal for that operation - in NATS core (subscribe), if the server returns an error to a subscription, that subscription is finished.

Possibly a better approach for you is to monitor the status:

```typescript
  const _ = (async () => {
    for await (const s of nc.status()) {
      console.log(s);
    }
  })();

  const sub = nc.subscribe("bar", {});
  const done = (async () => {
    for await(const m of sub) {
      //
    }
  })().catch((err) => {
    console.log(`sub failed`, err);
  })
```

If there were a problem with the subscription, there would be an async status generated:

```javascript
{
  type: "error",
  data: "PERMISSIONS_VIOLATION",
  permissionContext: { operation: "subscription", subject: "bar" }
}
```

**Comment by aricart** [comment]
Please feel free to re-open if you have additional questions
