### ISSUE TITLE
NatsError: TIMEOUT

### ISSUE THREAD

**Issue by neverabsolute** [nats-io/nats.js#562]
Related to #540 and #538

Getting timeout errors when trying to concurrently process requests/pubs in a subscribed handler.
nats client version: `"nats": "^2.12.1"`
nats server version: latest docker image

The idea is I have folders of async handlers by subject that perform various actions like so:

```ts
export default {
	subject: "data.hello",
	handler: async (nc, msg, data) => {
		// do something here
	}
} as NatsHandler<"data.hello">;
```

Below is what I use in the subscriber, works great to execute handlers, as long as they execute in <1s

```ts
export default async () => {
	const nc = await connectNats();

	console.log(`NATS: Connected on ${NATS_URL}`);
	initLogging(nc);

	const actions: NatsHandler<NatsEventSubject>[] = await Promise.all(
		resolve(dirname(import.meta.url) + "/actions/**/*.{ts,js}").map(f =>
			import(f).then(m => m.default)
		)
	);

	nc.subscribe(prefix("data.>"), {
		callback: async (err, msg) => {
			if (err) {
				console.error(err);
				return;
			}

			const subject = unprefix(msg.subject);

			if (!Object.keys(natsEventDescriptions).includes(subject)) {
				console.error(`Unknown event: ${subject}`);
				return;
			}

			const message = Buffer.from(msg.data).toString();
			const data = JSON.parse(message) as NatsEventKey[NatsEventSubject];

			await Promise.all(
				actions
					.filter(a => a.subject === subject)
					.map(a => a.handler(nc, msg, data))
			);
		}
	});
};
```

But let's say I have a particularly demanding function, or I do something like:
`await new Promise(resolve => setTimeout(resolve, 5000));`

Even if I try increasing the timeout in the request like so, it still times out.
`await nc.request(subject, Buffer.from(JSON.stringify(data)), { timeout: 10000 });`

I've noticed that if I convert the callback to an entirely synchronous handler like so:

```ts
	callback: (err, msg) => {
			if (err) {
				console.error(err);
				return;
			}

			const subject = unprefix(msg.subject);

			if (!Object.keys(natsEventDescriptions).includes(subject)) {
				console.error(`Unknown event: ${subject}`);
				return;
			}

			const message = Buffer.from(msg.data).toString();
			const data = JSON.parse(message) as NatsEventKey[NatsEventSubject];

			actions
				.filter(a => a.subject === subject)
				.map(a => a.handler(nc, msg, data))
			);
```

I can make requests process for ~10 seconds before they time out (assuming the `nc.request` call has a high enough timeout set)

Is there something I'm missing mechanic-wise? I've tried to emulate the suggestions you provided in other related issues, but they didn't seem to help (aside from making the callback non-blocking/async)

**Comment by aricart** [comment]
There are a few things we want to cover here:

- If you make a request, the request times out if your subscription doesn't answer quickly enough. The time for this timeout is on the client side, and it starts when the client publishes the request.

- The next one is you are using callbacks, but you are passing an async handler to it, but callbacks are not async, so if your particular case you don't seem to be blocking the loop or the client (this is good), because your callback is going to start processing your request before your handler returns (you are awaiting several promises)

So this pattern is actually very good, however your use of it is not correct and could yield to some failure that will be hard to track on your side. 


Now the other side of this equation is that because you are using a callback, messages are processed on the event loop where the message was received, that means that if the socket read a bunch of data, say 1000 messages, it will process those 1000 messages before that event loop completes. If you are responding, messages will be buffered for dispatch on the "next" event loop unless that buffer has reached 32K of data, in which case then it will be sent to the socket right then and there.

What this means is if your responses are fairly small and you don't reach that threshold, responses won't go out until message 1000 has processed (which will now be a factor of how long it takes all requests in to be processed)


- I would want to see how long it takes to process a single message.
- I would change your handler to be an iterator (for await(const m of sub))
- I would make sure you do not block the iterator (that is you will call a function that will handle the request but will not block the loop. If you do any `await` inside of the body of the loop, the loop won't process any messages until that loop iteration is done - ie if it takes 500 millis to process your response, by the time you process the 4th message all messages waiting will start timing out.

If you don't block, processing of buffered messages will be very quick (the async operation may still wait - if you are waiting on native resources they are prob handled in a separate thread) so that means it will be more lively and the even thread will be able to process many many messages. If the processing is still on the javascript side, well, it's single threaded, so you either need to look at workers and scaling your subscription horizontally using a queue subscriber, so reduce your backlog.


Lastly, in your use case there, you are taking the payload from the message creating a buffer by copying all the data from the message to yield the string, and then you are parsing the string as JSON. You can reduce that by using the JSONCodec provided by the library to parse your JSON.

**Comment by neverabsolute** [comment]
Thanks for the information! I've started using your suggestions and noticed an immediate difference.

- processing a single message (I think this is what you mean) seems to take ~1ms, although if I make the `action.handler` blocking via `await` it usually takes more like 200ms (depending on what is in the action itself)

If I convert to an iterator like you mentioned:

```ts
const sub = nc.subscribe(prefix("data.>"));
const sc = StringCodec();

(async () => {
	for await (const msg of sub) {
		const subject = unprefix(msg.subject);
		const action = actions.find(a => a.subject === subject);
		
		if (!action) continue;

		const data = JSON.parse(sc.decode(msg.data));
		console.log(`NATS: Received ${subject}`, data);
		try {
			const now = Date.now();
			action.handler(nc, msg, data);
			console.debug(`NATS: Handled ${subject} in ${Date.now() - now}ms`);
		} catch (e) {
			console.error(`NATS: Error handling ${subject}`, e);
		}
	}
})();
```
It seems to work fine, which is a major plus. I notice that the timeouts I set in `nc.request` are no longer respected (i.e. if downstream of the sync `action.handler` call I have an `await new Promise(resolve => setTimeout(resolve, 5000));` and the `nc.request` has a 4000ms timeout, nothing bad happens and it just resolves eventually).

Not a huge problem IMO? Although if downstream in the handler something is awaited for >10s it will still throw a hard error upstream where it was requested, regardless of the timeout set. Can probably just be avoided by using `await` with more strict timeouts on blocking operations.

**Comment by aricart** [comment]
the timeout should be an is observed - unless the timeout fires after the response resolves - in which case the Promise.race will yield the first one.

The question is what is the execution of the downstream - again, if you are chaining multiple requests the result is always going to be the sum of them.

What you are doing is allowing for more "concurrency" - the way promises resolve is not as intuitive as you think. Here's a small writeup https://github.com/nats-io/nats.js/blob/main/README.md#async-vs-callbacks

**Comment by neverabsolute** [comment]
Gotcha, thanks for the information, I think I've got it figured out!
